### PR TITLE
Add a Provenance page

### PR DESCRIPTION
**Pull request by zoenolan**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Does your submission pass tests?
* [x] Have you linted your code locally prior to submission?

### CODE REVIEW

**Comment by zoenolan** [comment]
Fixes #67

**Comment by rehat101** [comment]
Notice how you the page refreshes when you go in the Provenance page. It's because you're using an anchor tag which doesn't respect the history state that's provided by `react-router-dom`

You should use `Link` component provided by `react-router-dom` for redirecting users to diff routes. 

```javascript
import { Link } from 'react-router-dom;
 
<Link to="/editions/ef-painful/provenance">Provenance</Link>
```

**Comment by rehat101** [comment]
Looks good - Just thinking... if we need a complete new component for Provenance? There are some repeatable components in there that might change which can also result in changing the provenance page manually. 

We need "Layout" component that will wrap in both scenarios. An Artwork page and a Provenance page. Which brings me to another question, Do we need a physical route to the provenance page? Should user link to provenance page?

**Comment by zoenolan** [comment]
I think it would be nice to be able to link to the provenance page. For email receipts.

As for factoring out common code. Yes. Part of my thinking around https://github.com/axna/zien/issues/72 was to wrap everything about an edition, so we can have multiple once

**Pull request merged**
