### PR TITLE
 Update the EditionID

### PR DESCRIPTION
**Pull request by zoenolan**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Does your submission pass tests?
* [x] Have you linted your code locally prior to submission?

### CODE REVIEW

**Comment by rehat101** [comment]
I use the `editionid` to fetch fields from Airtable. 

The `editionid` before the change was basically an internal primary key that Airtable uses to send Claim Edition record back.

Here's what the api call looks like:
`https://api.airtable.com/v0/appQiqpkMQ8Y3SClV/AllScarceEditions/recKLS0HMwWNxwR6m `

Here's the response I get back:
```{
    "id": "recKLS0HMwWNxwR6m",
    "fields": {
        "DropDate": "2019-08-25",
        "Year": 2019,
.... }
```

As you can see the first `id` is what the primary key is to look up the record on Airtable. 

[Here](https://airtable.com/appQiqpkMQ8Y3SClV/api/docs#curl/table:allscarceeditions:retrieve) is the api documentation

I will need to find an alternative solution to send actual IDs via Typeform query params. 

I'm happy to approve the request if you change the `editionid` back as it will break the app.

**Comment by zoenolan** [comment]
We can just make our primary key the same as Airtable then if that would be the simplest solution

**Comment by rehat101** [comment]
Yea, if we can make the field `editionID` as our primary key for lookup that'd be great. I can just use that. 

Let me know when you update it. I'll do some local test and approve this PR.

**Comment by zoenolan** [comment]
Updated the EditionID in AllScarceEditions to use the same value as AirTable's API, closing this PR but created another one for the typo https://github.com/axna/zien/pull/144

**Pull request closed without merging**
